name: Azure Terraform Workflow

on: 
  workflow_dispatch: 
  push:
    branches: 
        - master
        -  'workflow/*'
  
jobs:
  terraform:
    name: Terraform Deployment to Azure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: virtual_network
        
    - name: Terraform Init
      run: terraform init
      working-directory: virtual_network

    - name: Terraform Validate
      run: terraform validate
      working-directory: virtual_network

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: virtual_network

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve
      working-directory: virtual_network

