name: Azure Terraform Workflow

on: 
  push:
    branches: 
        - master
        -  'workflow/*'
  
jobs:
  terraform:
    name: Terraform Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      run: terraform fmt -check
        
    - name: Terraform Init
      run: terraform init
      working-directory: virtual_network

    - name: Terraform Validate
      run: terraform validate
      working-directory: virtual_network

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: virtual_network

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve
      working-directory: virtual_network

